apiVersion: apps/v1
kind: Deployment
metadata:
  name: mke-aas1-deploy
  namespace: srv-mke-aas1
  labels:
    app: mke-aas1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mke-aas1-deploy
  template:
    metadata:
      labels:
        app: mke-aas1-deploy
    spec:
      containers:
      - name: hierarchy-matching-api
        image: mtkomcr.mediatek.inc/srv-mke-aas1/hierarchy-matching-api:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
      - name: mke-aas1-harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mke-aas1-service
  namespace: srv-mke-aas1
  labels:
    app: mke-aas1-deploy
spec:
  type: NodePort
  selector:
    app: mke-aas1-deploy
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
